"""
Virtual ICU v2.0 - PDF Report Generator
Generate clinical reports for patient cases
"""

from datetime import datetime, timedelta
from typing import Dict, List, Optional
import io


class PDFReportGenerator:
    """
    Generate professional PDF clinical reports
    """
    
    def __init__(self):
        self.report_template = """
        VIRTUAL ICU CLINICAL REPORT
        ════════════════════════════════════════════════════════════════
        
        PATIENT INFORMATION
        ────────────────────────────────────────────────────────────────
        Patient ID: {patient_id}
        Scenario: {scenario}
        Age: {age} years
        Report Date: {report_date}
        Report Time: {report_time}
        
        
        EXECUTIVE SUMMARY
        ────────────────────────────────────────────────────────────────
        {summary}
        
        
        VITAL SIGNS SUMMARY
        ────────────────────────────────────────────────────────────────
        
        Current Vitals:
          • Heart Rate: {current_hr} bpm
          • Systolic BP: {current_sbp} mmHg
          • Respiratory Rate: {current_rr} /min
          • SpO2: {current_spo2}%
          • Temperature: {current_temp}°C
          • Alert Status: {alert_status}
        
        Vital Ranges Over Monitoring Period:
          • HR: {hr_min}-{hr_max} bpm (baseline: ~80)
          • SBP: {sbp_min}-{sbp_max} mmHg (baseline: ~120)
          • RR: {rr_min}-{rr_max} /min (baseline: ~14)
          • SpO2: {spo2_min}-{spo2_max}% (baseline: ~98)
        
        
        CLINICAL SCORES
        ────────────────────────────────────────────────────────────────
        
        NEWS2 Score (National Early Warning Score 2)
          Score: {news2_score}/20
          Risk Level: {news2_risk}
          Status: {news2_status}
        
        qSOFA Score (Quick Sequential Organ Failure Assessment)
          Score: {qsofa_score}/3
          Sepsis Investigation: {qsofa_investigation}
          Status: {qsofa_status}
        
        CART Score (Cardiac Arrest Risk Triage)
          Score: {cart_score}/20
          Risk Category: {cart_risk}
          Percentile: {cart_percentile}
        
        
        CLINICAL RECOMMENDATIONS
        ────────────────────────────────────────────────────────────────
        
        Urgency Level: {urgency_level}
        
        Actions Recommended ({num_actions}):
        {recommendations}
        
        
        24-HOUR FORECAST
        ────────────────────────────────────────────────────────────────
        
        Deterioration Risk: {deterioration_risk}
        Confidence: {forecast_confidence}%
        
        Predicted Vital Trends:
          • Heart Rate: {forecast_hr_trend}
          • Blood Pressure: {forecast_bp_trend}
          • SpO2: {forecast_spo2_trend}
          • Respiratory Rate: {forecast_rr_trend}
        
        Recommended Actions for Next 24 Hours:
        {forecast_recommendations}
        
        
        CLINICAL PEARLS & EDUCATIONAL NOTES
        ────────────────────────────────────────────────────────────────
        
        {clinical_pearls}
        
        
        DECISION SUPPORT
        ────────────────────────────────────────────────────────────────
        
        Key Clinical Findings:
        {key_findings}
        
        Clinical Pathways to Consider:
        {clinical_pathways}
        
        Evidence-Based Interventions:
        {interventions}
        
        
        MONITORING RECOMMENDATIONS
        ────────────────────────────────────────────────────────────────
        
        Suggested Monitoring Frequency: {monitoring_frequency}
        ICU Consideration: {icu_consideration}
        Specialist Consultation: {specialist_consultation}
        
        
        APPENDIX: SCORING SYSTEM REFERENCE
        ────────────────────────────────────────────────────────────────
        
        NEWS2 Components:
          • Respiratory Rate scoring (0-3 points)
          • SpO2 scoring (0-3 points, with Scale 2 for COPD)
          • Temperature scoring (0-2 points)
          • Systolic BP scoring (0-2 points)
          • Heart Rate scoring (0-2 points)
          • Consciousness Level (0 or 3 points)
          • Oxygen Therapy (0 or 2 points)
        
        qSOFA Components:
          • Altered mental status (1 point if present)
          • Systolic BP ≤100 mmHg (1 point)
          • Respiratory rate ≥22/min (1 point)
        
        CART Components:
          • Age-based scoring
          • Hemodynamic parameters
          • Respiratory parameters
          • Consciousness assessment
        
        
        REPORT METADATA
        ────────────────────────────────────────────────────────────────
        Generated by: Virtual ICU v2.0
        System Version: {version}
        Report Type: Clinical Summary
        Data Classification: Educational/Synthetic
        
        DISCLAIMER: This report is generated from SYNTHETIC DATA for
        educational purposes only. It is not intended for real patient
        care or clinical decision-making.
        
        ════════════════════════════════════════════════════════════════
        """
    
    def generate_report(self, 
                       patient_data: Dict,
                       vitals_history: List[Dict],
                       scores: Dict,
                       forecast: Dict,
                       recommendations: List[Dict]) -> str:
        """
        Generate comprehensive clinical report
        
        Args:
            patient_data: Patient demographic info
            vitals_history: Historical vital signs
            scores: Clinical scores (NEWS2, qSOFA, CART)
            forecast: 24-hour forecast
            recommendations: Clinical recommendations
        
        Returns:
            Formatted report text
        """
        
        # Extract current vitals
        current_vitals = vitals_history[-1] if vitals_history else {}
        
        # Calculate statistics
        stats = self._calculate_statistics(vitals_history)
        
        # Format recommendations
        formatted_recs = self._format_recommendations(recommendations)
        
        # Generate forecast summaries
        forecast_summary = self._summarize_forecast(forecast)
        
        # Generate clinical pearls
        clinical_pearls = self._generate_clinical_pearls(scores, patient_data)
        
        # Generate key findings
        key_findings = self._extract_key_findings(scores, vitals_history)
        
        # Format report
        report = self.report_template.format(
            patient_id=patient_data.get('patient_id', 'P001'),
            scenario=patient_data.get('scenario', 'Unknown'),
            age=patient_data.get('age', 65),
            report_date=datetime.now().strftime('%Y-%m-%d'),
            report_time=datetime.now().strftime('%H:%M:%S'),
            
            summary=self._generate_summary(scores),
            
            current_hr=int(current_vitals.get('heart_rate', 80)),
            current_sbp=int(current_vitals.get('systolic_bp', 120)),
            current_rr=int(current_vitals.get('respiratory_rate', 16)),
            current_spo2=int(current_vitals.get('spo2', 98)),
            current_temp=round(current_vitals.get('temperature', 37.0), 1),
            alert_status=current_vitals.get('alert_status', 'Alert'),
            
            hr_min=int(stats.get('hr_min', 60)),
            hr_max=int(stats.get('hr_max', 120)),
            sbp_min=int(stats.get('sbp_min', 100)),
            sbp_max=int(stats.get('sbp_max', 140)),
            rr_min=int(stats.get('rr_min', 12)),
            rr_max=int(stats.get('rr_max', 25)),
            spo2_min=int(stats.get('spo2_min', 90)),
            spo2_max=int(stats.get('spo2_max', 99)),
            
            news2_score=scores.get('news2', {}).get('total', 0),
            news2_risk=scores.get('news2', {}).get('risk_level', 'Unknown'),
            news2_status="High Risk - Urgent Evaluation" if scores.get('news2', {}).get('risk_level') == 'High' else "Monitor Closely",
            
            qsofa_score=scores.get('qsofa', {}).get('total', 0),
            qsofa_investigation="Yes - Sepsis Protocol" if scores.get('qsofa', {}).get('needs_investigation') else "No",
            qsofa_status="Sepsis Alert" if scores.get('qsofa', {}).get('needs_investigation') else "Low Risk",
            
            cart_score=scores.get('cart', {}).get('total', 0),
            cart_risk=scores.get('cart', {}).get('risk_category', 'Unknown'),
            cart_percentile=int(scores.get('cart', {}).get('percentile', 50)),
            
            urgency_level=self._determine_urgency(scores),
            num_actions=len(recommendations),
            recommendations=formatted_recs,
            
            deterioration_risk=forecast.get('deterioration_risk', {}).get('risk_level', 'Unknown'),
            forecast_confidence=int(forecast.get('confidence', 0.8) * 100),
            
            forecast_hr_trend=forecast_summary.get('hr_trend', 'Stable'),
            forecast_bp_trend=forecast_summary.get('bp_trend', 'Stable'),
            forecast_spo2_trend=forecast_summary.get('spo2_trend', 'Stable'),
            forecast_rr_trend=forecast_summary.get('rr_trend', 'Stable'),
            
            forecast_recommendations=forecast_summary.get('recommendations', 'Continue current management'),
            
            clinical_pearls=clinical_pearls,
            key_findings=key_findings,
            clinical_pathways=self._suggest_clinical_pathways(scores),
            interventions=self._suggest_interventions(scores),
            
            monitoring_frequency=self._suggest_monitoring(scores),
            icu_consideration="Consider ICU Escalation" if self._determine_urgency(scores) == 'High' else "Continue current level of care",
            specialist_consultation="Infectious Disease" if scores.get('qsofa', {}).get('needs_investigation') else "None urgently needed",
            
            version="2.0 (Advanced Features)"
        )
        
        return report
    
    def _calculate_statistics(self, vitals_history: List[Dict]) -> Dict:
        """Calculate vital statistics"""
        if not vitals_history:
            return {}
        
        stats = {}
        
        vitals_to_track = ['heart_rate', 'systolic_bp', 'respiratory_rate', 'spo2', 'temperature']
        
        for vital in vitals_to_track:
            values = [v.get(vital, 0) for v in vitals_history if vital in v]
            
            if values:
                stats[f'{vital}_min'] = min(values)
                stats[f'{vital}_max'] = max(values)
                stats[f'{vital}_mean'] = sum(values) / len(values)
        
        return stats
    
    def _format_recommendations(self, recommendations: List[Dict]) -> str:
        """Format recommendations for report"""
        if not recommendations:
            return "  • Continue routine monitoring"
        
        formatted = []
        for i, rec in enumerate(recommendations, 1):
            priority = rec.get('priority', 5)
            action = rec.get('action', 'Unknown action')
            formatted.append(f"  {i}. {action}")
        
        return '\n'.join(formatted)
    
    def _summarize_forecast(self, forecast: Dict) -> Dict:
        """Summarize 24-hour forecast"""
        summary = {
            'hr_trend': 'Increasing' if forecast.get('trend_analysis', {}).get('heart_rate', 0) > 5 else 'Stable',
            'bp_trend': 'Decreasing' if forecast.get('trend_analysis', {}).get('systolic_bp', 0) < -5 else 'Stable',
            'spo2_trend': 'Decreasing' if forecast.get('trend_analysis', {}).get('spo2', 0) < -1 else 'Stable',
            'rr_trend': 'Increasing' if forecast.get('trend_analysis', {}).get('respiratory_rate', 0) > 2 else 'Stable',
            'recommendations': self._forecast_to_recommendations(forecast)
        }
        return summary
    
    def _forecast_to_recommendations(self, forecast: Dict) -> str:
        """Convert forecast to recommendations"""
        risk = forecast.get('deterioration_risk', {}).get('risk_level', 'Low')
        
        if risk == 'Low':
            return "• Continue routine monitoring\n        • Reassess in 4 hours"
        elif risk == 'Medium':
            return "• Increase monitoring frequency\n        • Prepare for possible escalation"
        elif risk == 'High':
            return "• Intensive continuous monitoring\n        • Prepare for ICU transfer"
        else:
            return "• IMMEDIATE physician notification\n        • Prepare for emergency intervention"
    
    def _generate_summary(self, scores: Dict) -> str:
        """Generate executive summary"""
        news2_risk = scores.get('news2', {}).get('risk_level', 'Unknown')
        qsofa_sep = scores.get('qsofa', {}).get('needs_investigation', False)
        cart_risk = scores.get('cart', {}).get('risk_category', 'Unknown')
        
        summary = f"Patient presenting with {news2_risk.lower()} risk on NEWS2 scoring."
        
        if qsofa_sep:
            summary += " Sepsis protocol recommended based on qSOFA criteria."
        
        summary += f" Cardiac arrest risk is {cart_risk.lower()}."
        
        return summary
    
    def _generate_clinical_pearls(self, scores: Dict, patient_data: Dict) -> str:
        """Generate educational clinical pearls"""
        pearls = []
        
        news2_risk = scores.get('news2', {}).get('risk_level', 'Unknown')
        if news2_risk == 'High':
            pearls.append("• NEWS2 ≥7 indicates high risk - escalate promptly")
        
        if scores.get('qsofa', {}).get('needs_investigation'):
            pearls.append("• qSOFA ≥2 associated with 9.4-15.4% in-hospital mortality")
            pearls.append("• Blood cultures and lactate must be obtained within 1 hour")
        
        if scores.get('cart', {}).get('risk_category') == 'High':
            pearls.append("• CART >75th percentile warrants intensive monitoring")
        
        age = patient_data.get('age', 65)
        if age > 75:
            pearls.append("• Elderly patients may have atypical presentations")
        
        if not pearls:
            pearls.append("• Continue evidence-based monitoring")
        
        return '\n        '.join(pearls)
    
    def _extract_key_findings(self, scores: Dict, vitals_history: List[Dict]) -> str:
        """Extract key clinical findings"""
        findings = []
        
        if vitals_history:
            recent = vitals_history[-1]
            if recent.get('heart_rate', 80) > 120:
                findings.append("• Tachycardia present")
            if recent.get('systolic_bp', 120) < 100:
                findings.append("• Hypotension present")
            if recent.get('spo2', 98) < 92:
                findings.append("• Hypoxemia present")
            if recent.get('respiratory_rate', 16) > 24:
                findings.append("• Tachypnea present")
        
        if not findings:
            findings.append("• Vital signs relatively stable")
        
        return '\n        '.join(findings)
    
    def _determine_urgency(self, scores: Dict) -> str:
        """Determine overall urgency"""
        news2_risk = scores.get('news2', {}).get('risk_level', 'Low')
        
        if news2_risk == 'High':
            return 'High'
        elif news2_risk == 'Medium':
            return 'Medium'
        else:
            return 'Low'
    
    def _suggest_clinical_pathways(self, scores: Dict) -> str:
        """Suggest clinical pathways"""
        pathways = []
        
        if scores.get('qsofa', {}).get('needs_investigation'):
            pathways.append("• Sepsis-3 Bundle Protocol")
        
        if scores.get('cart', {}).get('risk_category') == 'High':
            pathways.append("• Cardiac Monitoring Protocol")
        
        if not pathways:
            pathways.append("• Standard ICU Monitoring Protocol")
        
        return '\n        '.join(pathways)
    
    def _suggest_interventions(self, scores: Dict) -> str:
        """Suggest evidence-based interventions"""
        interventions = []
        
        news2_risk = scores.get('news2', {}).get('risk_level', 'Low')
        if news2_risk in ['Medium', 'High']:
            interventions.append("• Review and escalate care level")
        
        if scores.get('qsofa', {}).get('needs_investigation'):
            interventions.append("• Blood cultures and lactate measurement")
            interventions.append("• Broad-spectrum antibiotics within 1 hour")
            interventions.append("• IV fluid resuscitation (30 mL/kg)")
        
        if not interventions:
            interventions.append("• Continue current management")
        
        return '\n        '.join(interventions)
    
    def _suggest_monitoring(self, scores: Dict) -> str:
        """Suggest monitoring frequency"""
        news2_risk = scores.get('news2', {}).get('risk_level', 'Low')
        
        if news2_risk == 'High':
            return "Continuous monitoring with vital signs q15min minimum"
        elif news2_risk == 'Medium':
            return "Hourly vital signs and clinical assessment"
        else:
            return "4-6 hourly vital signs depending on clinical stability"
